import { Prisma } from '@prisma/client';

export const portfolioItems: Prisma.PortfolioItemCreateInput[] = [
  {
    title: 'E-Commerce Platform',
    description: 'A full-featured e-commerce platform built with Next.js, Stripe, and a headless CMS. Features include product filtering, cart management, user authentication, and payment processing.',
    category: 'Web Development',
    tags: ['Next.js', 'React', 'Stripe', 'Tailwind CSS', 'TypeScript'],
    images: [
      'https://res.cloudinary.com/demo/image/upload/v1612345678/portfolio/ecommerce-1.jpg',
      'https://res.cloudinary.com/demo/image/upload/v1612345678/portfolio/ecommerce-2.jpg',
      'https://res.cloudinary.com/demo/image/upload/v1612345678/portfolio/ecommerce-3.jpg',
    ],
    liveUrl: 'https://example-ecommerce.com',
    githubUrl: 'https://github.com/yadukrishnan/ecommerce-platform',
    featured: true,
    order: 1,
  },
  {
    title: 'AI-Powered Content Generator',
    description: 'An application that leverages OpenAI\'s GPT models to generate marketing content, blog posts, and social media captions. Includes a user-friendly interface and content management system.',
    category: 'AI Applications',
    tags: ['React', 'Node.js', 'OpenAI', 'Express', 'MongoDB'],
    images: [
      'https://res.cloudinary.com/demo/image/upload/v1612345678/portfolio/ai-content-1.jpg',
      'https://res.cloudinary.com/demo/image/upload/v1612345678/portfolio/ai-content-2.jpg',
    ],
    liveUrl: 'https://ai-content-generator.com',
    githubUrl: 'https://github.com/yadukrishnan/ai-content-generator',
    featured: true,
    order: 2,
  },
  {
    title: 'Real Estate Management System',
    description: 'A comprehensive real estate management system for property listings, tenant management, and financial tracking. Includes interactive maps, virtual tours, and automated notifications.',
    category: 'Web Applications',
    tags: ['React', 'Node.js', 'PostgreSQL', 'Google Maps API', 'Docker'],
    images: [
      'https://res.cloudinary.com/demo/image/upload/v1612345678/portfolio/realestate-1.jpg',
      'https://res.cloudinary.com/demo/image/upload/v1612345678/portfolio/realestate-2.jpg',
      'https://res.cloudinary.com/demo/image/upload/v1612345678/portfolio/realestate-3.jpg',
    ],
    liveUrl: 'https://realestate-management.com',
    featured: false,
    order: 3,
  },
  {
    title: 'Health & Fitness Tracker',
    description: 'A mobile-first application for tracking workouts, nutrition, and health metrics. Features include custom workout plans, progress visualization, and social sharing capabilities.',
    category: 'Mobile Applications',
    tags: ['React Native', 'Firebase', 'Redux', 'Health API', 'GraphQL'],
    images: [
      'https://res.cloudinary.com/demo/image/upload/v1612345678/portfolio/fitness-1.jpg',
      'https://res.cloudinary.com/demo/image/upload/v1612345678/portfolio/fitness-2.jpg',
    ],
    githubUrl: 'https://github.com/yadukrishnan/fitness-tracker',
    featured: false,
    order: 4,
  },
  {
    title: 'Cloud Infrastructure Automation',
    description: 'A set of infrastructure-as-code templates and automation scripts for AWS and Azure cloud environments. Includes CI/CD pipelines, security configurations, and cost optimization strategies.',
    category: 'DevOps',
    tags: ['Terraform', 'AWS', 'Azure', 'GitHub Actions', 'Kubernetes'],
    images: [
      'https://res.cloudinary.com/demo/image/upload/v1612345678/portfolio/cloud-1.jpg',
    ],
    githubUrl: 'https://github.com/yadukrishnan/cloud-automation',
    featured: false,
    order: 5,
  },
  {
    title: 'Educational Learning Platform',
    description: 'An interactive learning platform with course management, video lectures, quizzes, and progress tracking. Supports multiple user roles including students, instructors, and administrators.',
    category: 'Web Development',
    tags: ['Next.js', 'MongoDB', 'WebRTC', 'Socket.io', 'TypeScript'],
    images: [
      'https://res.cloudinary.com/demo/image/upload/v1612345678/portfolio/education-1.jpg',
      'https://res.cloudinary.com/demo/image/upload/v1612345678/portfolio/education-2.jpg',
    ],
    liveUrl: 'https://learning-platform-demo.com',
    githubUrl: 'https://github.com/yadukrishnan/learning-platform',
    featured: true,
    order: 6,
  },
  {
    title: 'Financial Dashboard',
    description: 'A comprehensive financial analytics dashboard with real-time data visualization, expense tracking, and investment portfolio management. Includes customizable widgets and reporting features.',
    category: 'Data Visualization',
    tags: ['React', 'D3.js', 'Node.js', 'PostgreSQL', 'Redis'],
    images: [
      'https://res.cloudinary.com/demo/image/upload/v1612345678/portfolio/finance-1.jpg',
      'https://res.cloudinary.com/demo/image/upload/v1612345678/portfolio/finance-2.jpg',
    ],
    liveUrl: 'https://finance-dashboard-demo.com',
    featured: false,
    order: 7,
  },
  {
    title: 'Social Media Management Tool',
    description: 'A comprehensive tool for scheduling, analyzing, and optimizing social media content across multiple platforms. Features include content calendar, analytics dashboard, and AI-powered content suggestions.',
    category: 'Web Applications',
    tags: ['Vue.js', 'Express', 'MongoDB', 'Social APIs', 'Chart.js'],
    images: [
      'https://res.cloudinary.com/demo/image/upload/v1612345678/portfolio/social-1.jpg',
      'https://res.cloudinary.com/demo/image/upload/v1612345678/portfolio/social-2.jpg',
    ],
    liveUrl: 'https://social-management-tool.com',
    githubUrl: 'https://github.com/yadukrishnan/social-media-tool',
    featured: false,
    order: 8,
  },
  {
    title: 'Inventory Management System',
    description: 'A robust inventory management system for small to medium businesses. Features include barcode scanning, stock alerts, supplier management, and detailed reporting.',
    category: 'Enterprise Solutions',
    tags: ['Angular', 'Java Spring', 'MySQL', 'Docker', 'Bootstrap'],
    images: [
      'https://res.cloudinary.com/demo/image/upload/v1612345678/portfolio/inventory-1.jpg',
    ],
    liveUrl: 'https://inventory-system-demo.com',
    featured: false,
    order: 9,
  },
  {
    title: 'Weather Visualization App',
    description: 'An interactive weather application with beautiful visualizations, forecasting, and historical data analysis. Includes location-based services and severe weather alerts.',
    category: 'Data Visualization',
    tags: ['React', 'D3.js', 'Weather API', 'Geolocation', 'PWA'],
    images: [
      'https://res.cloudinary.com/demo/image/upload/v1612345678/portfolio/weather-1.jpg',
      'https://res.cloudinary.com/demo/image/upload/v1612345678/portfolio/weather-2.jpg',
    ],
    liveUrl: 'https://weather-viz-app.com',
    githubUrl: 'https://github.com/yadukrishnan/weather-app',
    featured: false,
    order: 10,
  }
];